### ISSUE TITLE
Pequeños errores - Ace Attorney

### ISSUE THREAD

**Issue by WorstAquaPlayer** [Traducciones-Kurain/PWTrilogy-ESP#2]
**Issue original por:** [cristianmiu25](https://github.com/cristianmiu25)

Jugando los tres primeros casos de AA me he encontrado algunos errores ortográficos:

- **Caso 2:** Cuando hablamos con Maya, las opciones al preguntarle utilizan el posesivo Tu, cuando sería más correcto usar Su, ya que en todos los diálogos la tratamos de usted.
- **Caso 2:** Al hablar con Maya en el centro de detención, antes del primer juicio sale el mensaje _¿Va a usted a llevar mi caso?_, cuando debería ser _¿Va usted a llevar mi caso?_.
![caso2](https://user-images.githubusercontent.com/87035120/124645131-586c8d80-de93-11eb-9d44-e34e15aa9f7a.png)

- **Caso 3:** En el primer juicio, hablanco con la Sra. Oldbag, sale el mensaje _Dijeron que no tenían "nada ver con ello", ¿sabe?_, cuando debería ser _Dijeron que no tenían "nada que ver con ello", ¿sabe?_.
![caso3](https://user-images.githubusercontent.com/87035120/124645349-9f5a8300-de93-11eb-857d-29f1d264f8e0.png)

- **Caso 3:** En la segunda investigación, se utiliza varias veces la palabra _guión_ pero no debería llevar tilde.

**Comment by JauCR** [comment]
A excepción de lo de "guión", que no tenemos pensado cambiarlo porque cuando se publicaron estos juegos era correcto (igual que los demostrativos con tilde), todo lo demás ha sido corregido. ¡Muchas gracias!
