### ISSUE TITLE
Logros de Steam no se desbloquean correctamente

### ISSUE THREAD

**Issue by WorstAquaPlayer** [Traducciones-Kurain/PWTrilogy-ESP#3]
**Issue original por:** [CTPache](https://github.com/CTPache)

Hay que comprobar qué pasa con los logros siguientes:
- Lunchbox Specialist -> Check out every lunchbox Angel Starr has to offer. (PW: AA, Ep. 5)
- Um, Lotta Hair, Was It? -> Reply with "Lotta Hair" when talking to Lotta. (JFA, Ep. 2)
Es posible que otros logros tampoco funcionen, comprobarlos aquí: https://steamcommunity.com/sharedfiles/filedetails/?id=1816088288

**Comment by WorstAquaPlayer** [comment]
El logro "Lunchbox Specialist" ahora si puede ser desbloqueado en el parche a partir de la versión 1.0.3.

**Comment by NestorBech** [comment]
Hola, el logro "Jean's Foreign Language Course" no se desbloquea. Llevo varios intentos sin éxito y quizás sea por la traducción, ¿me pueden confirmar si es un bug o si se puede sacar con el parche? Gracias.

**Comment by WorstAquaPlayer** [comment]
> Hola, el logro "Jean's Foreign Language Course" no se desbloquea. Llevo varios intentos sin éxito y quizás sea por la traducción, ¿me pueden confirmar si es un bug o si se puede sacar con el parche? Gracias.

Efectivamente, era un bug de la traducción. Esto fue arreglado en la versión 1.0.5

**Comment by NestorBech** [comment]
Me sigue sin saltar, me salió el parche al iniciar el juego y me lo he descargado e incluso lo he instalado por mi cuenta y no hay manera (he instalado la 1.06, igual tengo que instalar la 1.05 y la 1.06)
Lo único que puedo estar haciendo mal es que estoy cargando las partes del logro y haciéndolo, en vez de pasármelo del tirón. Pero antes de volver a pasarme el caso entero, me quiero asegurar.
Por cierto, muchas gracias.

**Comment by WorstAquaPlayer** [comment]
> Me sigue sin saltar, me salió el parche al iniciar el juego y me lo he descargado e incluso lo he instalado por mi cuenta y no hay manera (he instalado la 1.06, igual tengo que instalar la 1.05 y la 1.06) Lo único que puedo estar haciendo mal es que estoy cargando las partes del logro y haciéndolo, en vez de pasármelo del tirón. Pero antes de volver a pasarme el caso entero, me quiero asegurar. Por cierto, muchas gracias.

No hace falta instalar gradualmente cada versión. La última contiene todos los cambios de los anteriores para evitar ese tedioso proceso.

Pequeño detalle, pero si cargas la partida, el juego mantiene en pequeña porción el script de la versión anterior.
En la traducción, el error específicamente se encontraba en esta parte del caso (pequeño spoiler alert, por si acaso):
Parte 4-1: Juicio

**Comment by NestorBech** [comment]
¡Ya está, me ha saltado el logro!
Cargué un archivo guardado en el final de la parte 3 y, antes de empezar el primer interrogatorio, me ha saltado. Curiosamente, no he tenido que hacer la parte del logro del interrogatorio.
¡Gracias!

**Comment by WorstAquaPlayer** [comment]
> ¡Ya está, me ha saltado el logro!
> Cargué un archivo guardado en el final de la parte 3 y, antes de empezar el primer interrogatorio, me ha saltado. Curiosamente, no he tenido que hacer la parte del logro del interrogatorio.
> ¡Gracias!

Genial! Gracias a ti por utilizar el parche.
