### ISSUE TITLE
Sugerencias traducción

### ISSUE THREAD

**Issue by Jozaca119988** [Traducciones-Kurain/PWTrilogy-ESP#5]
Hola, soy un poco nuevo en github así que no se si esto va por aquí. En la ficha de tradusquare decís que teníais pensado mejorar algunas cosas de la traducción original y que aceptabais preguntas y sugerencias en discord, así que ahí van:
En el primer caso:
1- Cuando habla el reloj de "El Pensador" en el cuadrito donde pone el nombre de quien habla pone "Despertador" mientras que el reloj no es referido nunca como "despertador" sino como "reloj". ¿No tendría más sentido cambiar el nombre a "Reloj"?
2- En el dialogo cuando habla dice: "Creo que son las 12:25" o algo así, no recuerdo la hora exacta. El caso es que entiendo que el chiste es que como es "El Pensador" debería decir "Pienso que son las 12:25" ya que en inglés "think" significa tanto "creer" como "pensar" pero esta claro que esta puesto para hacer un juego de palabras con el nombre del reloj. (Que ya se que el juego es un juego japonés y el idioma original sería japonés, no inglés, pero por lo que veo la traducción española es una traducción de la inglesa con sus cambios de localización)

**Comment by JauCR** [comment]
En general, no queremos editar el guion de la traducción oficial española, a menos a que sea para arreglar fallos ortográficos. Lo de "pienso que son las..." es una alternativa poco natural y en japonés tampoco hace la referencia a la estatua, simplemente "cree" que es esa hora, por lo que esto no se va a arreglar.
