### ISSUE TITLE
Habilitar soporte para la version de Microsoft Store(Game Pass)

### ISSUE THREAD

**Issue by Pointing8422** [Traducciones-Kurain/PWTrilogy-ESP#6]
Dicha version posee los mismos archivos que la de steam y puedes explorar su directorio, pero el parcheador no permite cambiar directorio. Por eso pido si se puede agregar tambien este directorio:
C:\XboxGames\Phoenix Wright- Ace Attorney Trilogy\Content

**Comment by WorstAquaPlayer** [comment]
Resumen simple: estamos trabajando en la versión de GamePass, todavía no lo tenemos listo.

Si bien la estructura de archivos es bastante similar a la versión de Steam, técnicamente el juego es diferente, por lo que tenemos que adaptar los archivos para que funcionen correctamente, así que no es una cuestión de simplemente cambiar carpetas.

**Comment by WorstAquaPlayer** [comment]
A partir de la versión 1.0.5, el parcheador ahora es capaz de reconocer esta versión y aplicar el parche correspondiente.
